"use client";
import React, { useState, useMemo, useEffect, useRef } from "react";
import { useTheme } from "next-themes";
import {
  BarChart, Bar, XAxis, YAxis, Cell, ResponsiveContainer, LabelList,
} from "recharts";
import {
  ArrowRight, ArrowLeft, TrendingDown, Zap, Check,
  Loader2, ChevronDown, ShieldCheck, Mail,
} from "lucide-react";
import WordMark from "./WordMark";
import ScopeLockForm from "./ScopeLockForm";

/**
 * THE START UP — Lead Leakage Calculator + AI Bottleneck Report
 * Golden-path stack proof asset. Drop into a React + Vite + TS project.
 *
 * Architecture notes for production:
 *  - The leak math below is DETERMINISTIC (never let an LLM compute money figures).
 *  - The personalized report is generated by Claude. In this demo it calls the
 *    Anthropic API directly; in production route it through your Hono proxy so the
 *    key stays server-side: POST /api/report  ->  Anthropic Messages API.
 *  - Lead capture (submitLead) should POST to your Hono proxy, which writes a row
 *    to your Monday.com "Inbound Leads" board via the Monday GraphQL API.
 */

// Response-time -> recoverable share of non-closing leads. Conservative, defensible.
const RESPONSE = {
  hour:    { label: "Within an hour", share: 0.0 },
  sameday: { label: "Same day",       share: 0.04 },
  nextday: { label: "Next day",       share: 0.09 },
  days:    { label: "2+ days",        share: 0.15 },
};

const INDUSTRIES = [
  "SaaS / Software", "Agency / Marketing", "Professional Services",
  "Recruitment / Staffing", "Distribution / Wholesale",
  "Financial Services", "Other",
];

const SYM = { USD: "$", ZAR: "R" };
const fmt = (n, cur) =>
  SYM[cur] + Math.round(isFinite(n) ? n : 0).toLocaleString("en-US");

// Count-up on reveal, respects reduced-motion.
function useCountUp(target, duration = 1100) {
  const [val, setVal] = useState(0);
  useEffect(() => {
    const reduce =
      typeof window !== "undefined" &&
      window.matchMedia &&
      window.matchMedia("(prefers-reduced-motion: reduce)").matches;
    if (reduce || !target) { setVal(target || 0); return; }
    let raf;
    const start = performance.now();
    const tick = (now) => {
      const p = Math.min((now - start) / duration, 1);
      const eased = 1 - Math.pow(1 - p, 3);
      setVal(target * eased);
      if (p < 1) raf = requestAnimationFrame(tick);
    };
    raf = requestAnimationFrame(tick);
    return () => cancelAnimationFrame(raf);
  }, [target, duration]);
  return val;
}

export default function LeadLeakageCalculator() {
  const [step, setStep] = useState("input"); // input | results | buildplan
  const [currency, setCurrency] = useState("USD");
  const [company, setCompany] = useState("");
  const [industry, setIndustry] = useState(INDUSTRIES[0]);
  const [leads, setLeads] = useState("");
  const [deal, setDeal] = useState("");
  const [close, setClose] = useState("");
  const [response, setResponse] = useState("nextday");

  const [email, setEmail] = useState("");
  const [report, setReport] = useState(null);
  const [loadingReport, setLoadingReport] = useState(false);
  const [leadCaptured, setLeadCaptured] = useState(false);
  const [showMethod, setShowMethod] = useState(false);

  // Direct links to the Build Plan step (e.g. from the homepage, or the old /scope-lock URL) skip the audit.
  useEffect(() => {
    const params = new URLSearchParams(window.location.search);
    if (params.get("step") === "buildplan") setStep("buildplan");
  }, []);

  // recharts renders raw SVG fill colors, not Tailwind classes — theme them manually.
  const { resolvedTheme } = useTheme();
  const [mounted, setMounted] = useState(false);
  useEffect(() => setMounted(true), []);
  const isDark = mounted ? resolvedTheme === "dark" : true;

  const calc = useMemo(() => {
    const L = parseFloat(leads) || 0;
    const D = parseFloat(deal) || 0;
    const C = (parseFloat(close) || 0) / 100;
    const share = RESPONSE[response].share;
    const valid = L > 0 && D > 0 && C > 0 && C <= 1;
    const nonClosing = L * (1 - C);
    const dealsMid = nonClosing * share;
    const monthlyLeak = dealsMid * D;
    const annualLeak = monthlyLeak * 12;
    const annualCaptured = L * C * D * 12;
    return {
      valid,
      dealsMid,
      monthlyLeak,
      annualLeak,
      annualCaptured,
      annualLeakLow: annualLeak * 0.7,
      annualLeakHigh: annualLeak * 1.3,
      minimal: share === 0,
    };
  }, [leads, deal, close, response]);

  const animated = useCountUp(step === "results" ? calc.annualLeak : 0);

  async function submitLead(payload) {
    try {
      await fetch("/api/lead", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      });
    } catch (e) {}
    setLeadCaptured(true);
  }

  async function generateReport() {
    setLoadingReport(true);
    const r = RESPONSE[response].label;
    const cur = SYM[currency];
    const prompt = `You are a senior revenue-operations consultant at "The Start Up", a firm that ships custom CRM lead-generation systems in 30 days. Write a sharp, personalized "Bottleneck Report" for a prospect who just ran our lead-leakage calculator.

Prospect details:
- Company: ${company || "the company"}
- Industry: ${industry}
- Monthly inbound leads: ${parseFloat(leads) || 0}
- Average deal value: ${cur}${parseFloat(deal) || 0}
- Current close rate: ${parseFloat(close) || 0}%
- Average lead response time: ${r}

We have ALREADY CALCULATED these figures. Use them EXACTLY. Do NOT invent or recompute any numbers:
- Recoverable deals per month: ${Math.round(calc.dealsMid)}
- Estimated monthly revenue leak: ${cur}${Math.round(calc.monthlyLeak).toLocaleString("en-US")}
- Estimated annual revenue leak: ${cur}${Math.round(calc.annualLeak).toLocaleString("en-US")}

Respond with ONLY valid JSON, no markdown fences, no preamble:
{
  "diagnosis": "2-3 sentences naming where leads leak for a company like this, specific to their industry and response time",
  "recommendations": ["three specific tactical fixes", "tailored to their numbers", "referencing real mechanics like response SLAs, automated routing, lead scoring, follow-up sequences"],
  "roi": "1-2 sentences on the upside of fixing this, referencing the annual leak figure",
  "closingLine": "1 sentence soft invitation to see how a custom CRM lead system plugs this in 30 days"
}
Be concrete and non-generic. No flattery, no filler.`;

    const fallback = {
      diagnosis: `For a ${industry.toLowerCase()} team fielding ${parseFloat(leads) || 0} leads a month with a ${r.toLowerCase()} response time, the leak isn't lead volume — it's the gap between a lead raising its hand and anyone reaching it. Interest decays fast, and a ${r.toLowerCase()} reply lets warm leads cool into the pipeline graveyard.`,
      recommendations: [
        "Set a sub-hour response SLA on inbound leads and make it visible — what gets measured on a board gets followed up.",
        "Auto-route every new lead to an owner the instant it lands, so nothing waits in a shared inbox for someone to notice it.",
        "Add automated scoring and a follow-up sequence so high-intent leads surface first and no one slips through after the first touch.",
      ],
      roi: `Closing even part of this gap puts an estimated ${fmt(calc.annualLeak, currency)} a year back in reach — without spending a cent more on lead generation.`,
      closingLine: "A custom CRM lead system can capture, route, and score every one of these automatically — live in 30 days.",
    };

    try {
      const res = await fetch("/api/report", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          company, industry, currency,
          leads: parseFloat(leads) || 0,
          deal: parseFloat(deal) || 0,
          closeRate: parseFloat(close) || 0,
          responseTime: RESPONSE[response].label,
          dealsPerMonth: calc.dealsMid,
          monthlyLeak: calc.monthlyLeak,
          annualLeak: calc.annualLeak,
        }),
      });
      const data = await res.json();
      setReport(data.report && data.report.diagnosis ? data.report : fallback);
    } catch (e) {
      setReport(fallback);
    } finally {
      setLoadingReport(false);
    }
  }

  function onReveal() {
    if (!calc.valid) return;
    setStep("results");
    setReport(null);
    setLeadCaptured(false);
    setEmail("");
  }

  function onGetReport() {
    if (!/.+@.+\..+/.test(email)) return;
    submitLead({
      company, industry, email, currency,
      leads: parseFloat(leads) || 0,
      deal: parseFloat(deal) || 0,
      closeRate: parseFloat(close) || 0,
      responseTime: RESPONSE[response].label,
      annualLeak: Math.round(calc.annualLeak),
    });
    generateReport();
  }

  const chartData = [
    { name: "You capture", value: Math.max(calc.annualCaptured, 0), label: fmt(calc.annualCaptured, currency), fill: "#059669" },
    { name: "Leaking out", value: Math.max(calc.annualLeak, 0), label: fmt(calc.annualLeak, currency), fill: "#f59e0b" },
  ];

  const inputBase =
    "w-full rounded-lg border border-slate-300 dark:border-slate-600 bg-white dark:bg-slate-800 px-3 py-2.5 text-slate-900 dark:text-slate-100 text-sm placeholder-slate-400 dark:placeholder-slate-500 focus:border-teal-500 focus:outline-none focus:ring-2 focus:ring-teal-100 dark:focus:ring-teal-900 transition-colors";
  const labelBase =
    "block text-xs font-medium uppercase tracking-wider text-slate-500 dark:text-slate-400 mb-1.5";

  // Carries the audit's numbers straight into the Build Plan step — same page, no re-typing.
  const buildPlanInitial = {
    ...(company ? { company } : {}),
    ...(calc.valid
      ? {
          goal: `Recover the ~${fmt(calc.annualLeak, currency)}/year we're losing to a slow sales cycle.`,
          bottleneck: `${industry} leads get a ${RESPONSE[response].label.toLowerCase()} response — deals cool before anyone follows up.`,
        }
      : {}),
  };

  return (
    <div className="min-h-screen w-full bg-slate-50 dark:bg-slate-950 text-slate-900 dark:text-slate-100 font-sans">
      <div className="mx-auto max-w-3xl px-5 py-10 sm:py-14">

        {/* Brand */}
        <div className="flex items-center justify-between mb-10">
          <a href="/"><WordMark /></a>
          <div className="hidden sm:block text-xs font-medium uppercase tracking-wider text-slate-400 dark:text-slate-500">
            {step === "buildplan" ? "Step 2 of 2 · Your Build Plan" : "Step 1 of 2 · Lead Leakage Audit"}
          </div>
        </div>

        {step === "input" && (
          <div>
            <h1 className="text-3xl sm:text-4xl font-semibold tracking-tight leading-tight">
              Your CRM isn't catching this —
              <span className="text-teal-400"> find out how much your sales cycle is leaking.</span>
            </h1>
            <p className="mt-3 text-slate-600 dark:text-slate-400 text-base max-w-xl">
              Most B2B teams don't lose deals to competitors — they lose them to a broken sales cycle: slow
              follow-up, no routing, nobody owning the next step. Answer four questions for an instant estimate. No call.
            </p>

            <div className="mt-8 rounded-2xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 p-5 sm:p-7 shadow-sm">
              {/* currency toggle */}
              <div className="flex items-center justify-between mb-5">
                <span className={labelBase + " mb-0"}>Your numbers</span>
                <div className="flex rounded-lg border border-slate-200 dark:border-slate-700 p-0.5 text-xs font-medium">
                  {["USD", "ZAR"].map((c) => (
                    <button
                      key={c}
                      onClick={() => setCurrency(c)}
                      className={
                        "px-3 py-1 rounded-md transition-colors " +
                        (currency === c
                          ? "bg-slate-900 dark:bg-teal-500 text-white dark:text-slate-950"
                          : "text-slate-500 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white")
                      }
                    >
                      {c}
                    </button>
                  ))}
                </div>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div className="sm:col-span-1">
                  <label className={labelBase}>Company name</label>
                  <input className={inputBase} value={company}
                    onChange={(e) => setCompany(e.target.value)}
                    placeholder="Acme Co." />
                </div>
                <div className="sm:col-span-1">
                  <label className={labelBase}>Industry</label>
                  <select className={inputBase} value={industry}
                    onChange={(e) => setIndustry(e.target.value)}>
                    {INDUSTRIES.map((i) => <option key={i}>{i}</option>)}
                  </select>
                </div>
                <div>
                  <label className={labelBase}>Monthly inbound leads</label>
                  <input className={inputBase} inputMode="numeric" value={leads}
                    onChange={(e) => setLeads(e.target.value.replace(/[^0-9.]/g, ""))}
                    placeholder="120" />
                </div>
                <div>
                  <label className={labelBase}>Average deal value ({SYM[currency]})</label>
                  <input className={inputBase} inputMode="numeric" value={deal}
                    onChange={(e) => setDeal(e.target.value.replace(/[^0-9.]/g, ""))}
                    placeholder="5,000" />
                </div>
                <div>
                  <label className={labelBase}>Current close rate (%)</label>
                  <input className={inputBase} inputMode="numeric" value={close}
                    onChange={(e) => setClose(e.target.value.replace(/[^0-9.]/g, ""))}
                    placeholder="20" />
                </div>
                <div>
                  <label className={labelBase}>Avg. lead response time</label>
                  <select className={inputBase} value={response}
                    onChange={(e) => setResponse(e.target.value)}>
                    {Object.entries(RESPONSE).map(([k, v]) =>
                      <option key={k} value={k}>{v.label}</option>)}
                  </select>
                </div>
              </div>

              <button
                onClick={onReveal}
                disabled={!calc.valid}
                className={
                  "mt-6 inline-flex w-full items-center justify-center gap-2 rounded-lg px-5 py-3 text-sm font-semibold transition-colors " +
                  (calc.valid
                    ? "bg-slate-900 dark:bg-teal-500 text-white dark:text-slate-950 hover:bg-slate-800 dark:hover:bg-teal-400"
                    : "bg-slate-200 dark:bg-slate-800 text-slate-400 dark:text-slate-500 cursor-not-allowed")
                }
              >
                Calculate my leak <ArrowRight className="h-4 w-4" />
              </button>
              {!calc.valid && (
                <p className="mt-2 text-center text-xs text-slate-400 dark:text-slate-500">
                  Enter leads, deal value, and a close rate between 1–100% to continue.
                </p>
              )}
            </div>
          </div>
        )}

        {step === "results" && (
          <div>
            <button onClick={() => setStep("input")}
              className="inline-flex items-center gap-1.5 text-sm text-slate-500 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white mb-6">
              <ArrowLeft className="h-4 w-4" /> Adjust my numbers
            </button>

            {/* Headline figure */}
            <div className="rounded-2xl border border-slate-200 dark:border-slate-700 bg-white dark:bg-slate-900 p-6 sm:p-8 shadow-sm">
              <div className="flex items-center gap-2 text-teal-700 dark:text-teal-400">
                <TrendingDown className="h-4 w-4" strokeWidth={2.5} />
                <span className="text-xs font-medium uppercase tracking-wider">
                  {calc.minimal ? "Estimated annual leak" : "You are likely losing, per year"}
                </span>
              </div>

              {calc.minimal ? (
                <div className="mt-3">
                  <div className="font-mono text-4xl sm:text-5xl font-semibold tracking-tight tabular-nums text-teal-600 dark:text-teal-400">
                    {fmt(0, currency)}
                  </div>
                  <p className="mt-3 text-slate-600 dark:text-slate-400 max-w-lg">
                    Your follow-up speed is already tight, so response-time leakage is minimal —
                    {company ? ` nice work, ${company}.` : " nice work."} The next gains are in
                    routing, scoring, and reporting. The report below maps them.
                  </p>
                </div>
              ) : (
                <div className="mt-3">
                  <div className="font-mono text-5xl sm:text-6xl font-semibold tracking-tight tabular-nums text-slate-900 dark:text-white">
                    {fmt(animated, currency)}
                  </div>
                  <p className="mt-3 text-slate-600 dark:text-slate-400 max-w-lg">
                    That's roughly <span className="font-semibold text-slate-900 dark:text-white">{Math.round(calc.dealsMid)} deals a month</span> slipping
                    away to slow follow-up{company ? `, ${company}` : ""} — about {fmt(calc.monthlyLeak, currency)} monthly.
                    Likely range {fmt(calc.annualLeakLow, currency)}–{fmt(calc.annualLeakHigh, currency)} a year.
                  </p>
                </div>
              )}

              {/* meter */}
              <div className="mt-6">
                <ResponsiveContainer width="100%" height={150}>
                  <BarChart data={chartData} layout="vertical"
                    margin={{ left: 0, right: 70, top: 4, bottom: 4 }}>
                    <XAxis type="number" hide />
                    <YAxis type="category" dataKey="name" width={90}
                      tick={{ fontSize: 12, fill: isDark ? "#94a3b8" : "#475569" }}
                      axisLine={false} tickLine={false} />
                    <Bar dataKey="value" radius={[5, 5, 5, 5]} barSize={26}>
                      {chartData.map((d, i) => <Cell key={i} fill={d.fill} />)}
                      <LabelList dataKey="label" position="right"
                        style={{ fontSize: 12, fontWeight: 600, fill: isDark ? "#f1f5f9" : "#0f172a" }} />
                    </Bar>
                  </BarChart>
                </ResponsiveContainer>
                <p className="text-xs text-slate-400 dark:text-slate-500">Annual revenue from these leads, captured vs. leaking.</p>
              </div>

              {/* methodology */}
              <button onClick={() => setShowMethod((v) => !v)}
                className="mt-4 inline-flex items-center gap-1 text-xs font-medium text-slate-500 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white">
                How this is calculated
                <ChevronDown className={"h-3.5 w-3.5 transition-transform " + (showMethod ? "rotate-180" : "")} />
              </button>
              {showMethod && (
                <p className="mt-2 text-xs leading-relaxed text-slate-500 dark:text-slate-400 max-w-xl">
                  We take your non-closing leads and apply a recoverable share based on lead-response
                  benchmarks: the slower the first touch, the larger the share of warm leads lost to
                  timing rather than genuine disinterest ({RESPONSE[response].label.toLowerCase()} ≈{" "}
                  {(RESPONSE[response].share * 100).toFixed(0)}% of non-closers). Recoverable deals ×
                  your average deal value × 12. An estimate, not a guarantee.
                </p>
              )}
            </div>

            {/* Report gate / report */}
            <div className="mt-6 rounded-2xl border border-slate-200 bg-slate-950 p-6 sm:p-8 shadow-sm text-slate-100">
              {!leadCaptured && (
                <div>
                  <div className="flex items-center gap-2 text-teal-400">
                    <Zap className="h-4 w-4" strokeWidth={2.5} />
                    <span className="text-xs font-medium uppercase tracking-wider">Your Bottleneck Report</span>
                  </div>
                  <h2 className="mt-2 text-2xl font-semibold tracking-tight">
                    Get the full diagnosis — instant, no call.
                  </h2>
                  <p className="mt-2 text-sm text-slate-400 max-w-lg">
                    A personalized breakdown of where your pipeline leaks and exactly how we'd plug it.
                    Written for {company || "your team"} in seconds.
                  </p>
                  <div className="mt-5 flex flex-col sm:flex-row gap-3">
                    <div className="relative flex-1">
                      <Mail className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-500" />
                      <input
                        className="w-full rounded-lg border border-slate-700 bg-slate-900 pl-9 pr-3 py-2.5 text-sm text-white placeholder-slate-500 focus:border-teal-500 focus:outline-none focus:ring-2 focus:ring-teal-900"
                        placeholder="you@company.com"
                        value={email}
                        onChange={(e) => setEmail(e.target.value)}
                      />
                    </div>
                    <button
                      onClick={onGetReport}
                      disabled={!/.+@.+\..+/.test(email)}
                      className={
                        "inline-flex items-center justify-center gap-2 rounded-lg px-5 py-2.5 text-sm font-semibold transition-colors " +
                        (/.+@.+\..+/.test(email)
                          ? "bg-teal-500 text-slate-950 hover:bg-teal-400"
                          : "bg-slate-700 text-slate-400 cursor-not-allowed")
                      }
                    >
                      Generate my report <ArrowRight className="h-4 w-4" />
                    </button>
                  </div>
                  <p className="mt-3 flex items-center gap-1.5 text-xs text-slate-500">
                    <ShieldCheck className="h-3.5 w-3.5" /> No spam. Your numbers stay yours.
                  </p>
                </div>
              )}

              {leadCaptured && loadingReport && (
                <div className="flex items-center gap-3 py-6 text-slate-300">
                  <Loader2 className="h-5 w-5 animate-spin text-teal-400" />
                  <span className="text-sm">Writing your Bottleneck Report…</span>
                </div>
              )}

              {leadCaptured && report && !loadingReport && (
                <div>
                  <div className="flex items-center gap-2 text-teal-400">
                    <Check className="h-4 w-4" strokeWidth={3} />
                    <span className="text-xs font-medium uppercase tracking-wider">
                      Bottleneck Report · {company || "Your team"}
                    </span>
                  </div>

                  <div className="mt-4">
                    <div className="text-xs font-medium uppercase tracking-wider text-slate-500 mb-1">Diagnosis</div>
                    <p className="text-sm leading-relaxed text-slate-200">{report.diagnosis}</p>
                  </div>

                  <div className="mt-5">
                    <div className="text-xs font-medium uppercase tracking-wider text-slate-500 mb-2">What we'd fix</div>
                    <ul className="space-y-2.5">
                      {report.recommendations.map((r, i) => (
                        <li key={i} className="flex gap-3 text-sm text-slate-200">
                          <span className="mt-0.5 flex h-5 w-5 flex-none items-center justify-center rounded-full bg-teal-500/15 text-teal-400 font-mono text-xs">
                            {i + 1}
                          </span>
                          <span className="leading-relaxed">{r}</span>
                        </li>
                      ))}
                    </ul>
                  </div>

                  <div className="mt-5 rounded-xl border border-teal-500/20 bg-teal-500/5 p-4">
                    <div className="text-xs font-medium uppercase tracking-wider text-teal-400 mb-1">The upside</div>
                    <p className="text-sm leading-relaxed text-slate-100">{report.roi}</p>
                  </div>

                  <div className="mt-6 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4 border-t border-slate-800 pt-5">
                    <p className="text-sm text-slate-300 max-w-sm">{report.closingLine}</p>
                    <button
                      type="button"
                      onClick={() => setStep("buildplan")}
                      className="inline-flex flex-none items-center justify-center gap-2 rounded-lg bg-white px-5 py-2.5 text-sm font-semibold text-slate-950 hover:bg-slate-200 transition-colors"
                    >
                      Turn this into my Build Plan <ArrowRight className="h-4 w-4" />
                    </button>
                  </div>
                </div>
              )}
            </div>

            <p className="mt-5 text-center text-xs text-slate-400 dark:text-slate-500">
              Estimates based on lead-response benchmarks. Built by The Start Up · CRM powered by Monday.com.
            </p>
          </div>
        )}

        {step === "buildplan" && (
          <div>
            <button
              type="button"
              onClick={() => setStep(calc.valid ? "results" : "input")}
              className="inline-flex items-center gap-1.5 text-sm text-slate-500 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white mb-6"
            >
              <ArrowLeft className="h-4 w-4" /> {calc.valid ? "Back to my leak report" : "Back to the audit"}
            </button>
            <ScopeLockForm
              embedded
              initialValues={buildPlanInitial}
              prefilledKeys={Object.keys(buildPlanInitial)}
            />
          </div>
        )}
      </div>
    </div>
  );
}
