import type { Metadata } from "next";
import Link from "next/link";
import { LegalPage, LegalSection } from "@/components/LegalPage";
import { COMPANY, LEGAL_UPDATED } from "@/lib/company";
import { SITE_URL } from "@/lib/site";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: `The terms that govern use of ${COMPANY.brand}’s website, free tools, and services.`,
  alternates: { canonical: `${SITE_URL}/terms` },
};

export default function TermsPage() {
  const email = <a href={`mailto:${COMPANY.supportEmail}`}>{COMPANY.supportEmail}</a>;

  return (
    <LegalPage title="Terms of Service" updated={LEGAL_UPDATED}>
      <LegalSection title="1. Who we are and what these terms cover">
        <p>
          {COMPANY.brand} is a service of {COMPANY.legalName} (“we”, “us”, “our”). These Terms govern your use of
          this website, including the Lead Leakage Calculator, the AI-generated Bottleneck Report, homepage tailoring,
          and the Build Plan questionnaire, and any services you buy from us.
        </p>
        <p>
          Project work is also governed by the Scope Lock Agreement and Service Proposal you sign. If that signed
          agreement conflicts with these Terms, the signed agreement controls.
        </p>
      </LegalSection>

      <LegalSection title="2. Free tools and AI-generated content">
        <p>
          The calculator’s figures are estimates based on the numbers you enter, not a guarantee of results. Reports,
          tailored copy, and suggestions generated by AI can be incomplete or wrong, so use your own judgment before
          acting on them.
        </p>
      </LegalSection>

      <LegalSection title="3. Build Plans, agreements, and electronic signatures">
        <p>
          Submitting a Build Plan doesn’t commit either of us to a project. A project begins when you sign the Scope
          Lock Agreement and pay the deposit.
        </p>
        <p>
          You agree that signing electronically by typing your name is a valid signature, legally binding under the
          U.S. Electronic Signatures in Global and National Commerce Act (E-SIGN Act) and the Uniform Electronic
          Transactions Act, and that we may deliver agreements, notices, and receipts to you electronically.
        </p>
      </LegalSection>

      <LegalSection title="4. Scope">
        <p>
          Your agreement is limited to the scope it describes. Changes require a written amendment and may affect the
          timeline and price.
        </p>
      </LegalSection>

      <LegalSection title="5. The 30-day build guarantee">
        <p>
          We commit to delivering a working system within 30 calendar days of your confirmed build start. If we miss
          that date for reasons attributable solely to us, you receive an additional 30 days of support at no cost.
        </p>
      </LegalSection>

      <LegalSection title="6. Fees and payment">
        <p>
          Prices are shown on the website and fixed in your agreement. Promotional pricing applies only to agreements
          signed while the promotion is offered.
        </p>
        <p>Payment follows three milestones:</p>
        <ul>
          <li><strong>10% deposit</strong> when you sign, which secures your start date.</li>
          <li><strong>80%</strong> when you approve the MVP plan, before the build continues.</li>
          <li><strong>Final 10%</strong> on delivery at the end of the 30-day build.</li>
        </ul>
        <p>
          Invoices are due within 5 business days, and overdue payments may pause the build. Payments are processed by
          Stripe; we never receive or store your full card details.
        </p>
      </LegalSection>

      <LegalSection title="7. Optional monthly plan">
        <p>
          You can opt in to an ongoing support plan, plus the third-party tools your system needs at cost, billed
          monthly through Stripe from the date shown at checkout. The plan continues month to month until you cancel.
          To cancel, email {email}; cancellation stops charges from your next billing date.
        </p>
      </LegalSection>

      <LegalSection title="8. Third-party tools and subscriptions">
        <p>
          You’re responsible for the cost of the third-party tools, platforms, APIs, and subscriptions needed to run
          and maintain your system, such as CRM or workspace subscriptions, hosting, domains, payment processing fees,
          and API usage. We list these, with estimated costs, before your build starts.
        </p>
      </LegalSection>

      <LegalSection title="9. Support period">
        <p>
          The support period covers active system support, bug fixes, optimization, and training. It begins on
          handover and doesn’t include new feature development.
        </p>
      </LegalSection>

      <LegalSection title="10. Ownership">
        <p>
          All custom configurations, automations, dashboards, and documentation we build for you become your property
          on final payment. We keep the rights to our reusable internal frameworks and methodologies.
        </p>
      </LegalSection>

      <LegalSection title="11. Confidentiality">
        <p>
          Both parties keep project details, business information, and proprietary data confidential and won’t
          disclose them to third parties without prior written consent.
        </p>
      </LegalSection>

      <LegalSection title="12. Cancellations and refunds">
        <p>
          Cancellations and refunds are covered by our <Link href="/refund-policy">Refund Policy</Link>.
        </p>
      </LegalSection>

      <LegalSection title="13. Acceptable use">
        <p>
          Don’t misuse the website. That includes attempting unauthorized access, disrupting or overloading the
          service, scraping it at scale, or submitting information that isn’t yours or that you don’t have the right
          to share.
        </p>
      </LegalSection>

      <LegalSection title="14. Disclaimers">
        <p>
          Except as expressly stated in a signed agreement, the website and free tools are provided “as is” and “as
          available”, without warranties of any kind, to the fullest extent permitted by law.
        </p>
      </LegalSection>

      <LegalSection title="15. Limitation of liability">
        <p>
          To the fullest extent permitted by law, our total liability is limited to the fees paid under the applicable
          agreement. We aren’t liable for indirect, consequential, or incidental losses.
        </p>
      </LegalSection>

      <LegalSection title="16. Force majeure">
        <p>
          Neither party is liable for delays caused by circumstances beyond its reasonable control, including natural
          disasters, government actions, or infrastructure failures.
        </p>
      </LegalSection>

      <LegalSection title="17. Governing law">
        <p>
          These Terms and any agreement with us are governed by the laws of the State of Texas and applicable U.S.
          federal law, without regard to conflict-of-law rules. Disputes will be heard in the state and federal courts
          located in Williamson County, Texas.
        </p>
      </LegalSection>

      <LegalSection title="18. Changes to these terms">
        <p>
          We may update these Terms from time to time. The date at the top shows the current version. Changes don’t
          alter agreements you’ve already signed.
        </p>
      </LegalSection>

      <LegalSection title="19. Contact">
        <p>Questions about these Terms? Email {email}.</p>
      </LegalSection>
    </LegalPage>
  );
}
